// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ThIhEFyvgsbETIzqwttczw2gm6_pSUQ',
    appId: '1:1069606813233:web:1421b239942bbbaf3d5f10',
    messagingSenderId: '1069606813233',
    projectId: 'envpro-40357',
    authDomain: 'envpro-40357.firebaseapp.com',
    databaseURL: 'https://envpro-40357-default-rtdb.firebaseio.com',
    storageBucket: 'envpro-40357.appspot.com',
    measurementId: 'G-BWJ260S0SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RDQR-AadvdZL3kG10RdcDAjXIws-xDo',
    appId: '1:1069606813233:android:102d470a3dd6209f3d5f10',
    messagingSenderId: '1069606813233',
    projectId: 'envpro-40357',
    databaseURL: 'https://envpro-40357-default-rtdb.firebaseio.com',
    storageBucket: 'envpro-40357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAg3l5LoK2_IIN13FRItrvyJgOzz1ybA4',
    appId: '1:1069606813233:ios:3caf2849b96d2b3e3d5f10',
    messagingSenderId: '1069606813233',
    projectId: 'envpro-40357',
    databaseURL: 'https://envpro-40357-default-rtdb.firebaseio.com',
    storageBucket: 'envpro-40357.appspot.com',
    iosBundleId: 'com.example.egApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAg3l5LoK2_IIN13FRItrvyJgOzz1ybA4',
    appId: '1:1069606813233:ios:3caf2849b96d2b3e3d5f10',
    messagingSenderId: '1069606813233',
    projectId: 'envpro-40357',
    databaseURL: 'https://envpro-40357-default-rtdb.firebaseio.com',
    storageBucket: 'envpro-40357.appspot.com',
    iosBundleId: 'com.example.egApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0ThIhEFyvgsbETIzqwttczw2gm6_pSUQ',
    appId: '1:1069606813233:web:4a24612607dd42743d5f10',
    messagingSenderId: '1069606813233',
    projectId: 'envpro-40357',
    authDomain: 'envpro-40357.firebaseapp.com',
    databaseURL: 'https://envpro-40357-default-rtdb.firebaseio.com',
    storageBucket: 'envpro-40357.appspot.com',
    measurementId: 'G-EQEZL596ZF',
  );
}
